// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: LocationsProto.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021

#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;

namespace LC.RA.TransferObjects
{
    /// <summary>Holder for reflection information generated from LocationsProto.proto</summary>
    public static partial class LocationsProtoReflection
    {
        #region Descriptor
        /// <summary>File descriptor for LocationsProto.proto</summary>
        public static pbr::FileDescriptor Descriptor
        {
            get { return descriptor; }
        }
        private static pbr::FileDescriptor descriptor;

        static LocationsProtoReflection()
        {
            byte[] descriptorData = global::System.Convert.FromBase64String(
                string.Concat(
                  "ChRMb2NhdGlvbnNQcm90by5wcm90bxIIdHV0b3JpYWwiQgoNTG9jYXRpb25Q",
                  "cm90bxIMCgRuYW1lGAEgASgJEg4KBnJlZ2lvbhgCIAEoCRITCgtncHNsb2Nh",
                  "dGlvbhgDIAEoCSI8Cg5Mb2NhdGlvbnNQcm90bxIqCglsb2NhdGlvbnMYASAD",
                  "KAsyFy50dXRvcmlhbC5Mb2NhdGlvblByb3RvQhiqAhVMQy5SQS5UcmFuc2Zl",
                  "ck9iamVjdHNiBnByb3RvMw=="));
            descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
                new pbr::FileDescriptor[] { },
                new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::LC.RA.TransferObjects.LocationProto), global::LC.RA.TransferObjects.LocationProto.Parser, new[]{ "Name", "Region", "Gpslocation" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::LC.RA.TransferObjects.LocationsProto), global::LC.RA.TransferObjects.LocationsProto.Parser, new[]{ "Locations" }, null, null, null)
                }));
        }
        #endregion
    }

    #region Messages
    /// <summary>
    /// [START messages]
    /// </summary>
    public sealed partial class LocationProto : pb::IMessage<LocationProto>
    {
        private static readonly pb::MessageParser<LocationProto> _parser = new pb::MessageParser<LocationProto>(() => new LocationProto());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<LocationProto> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor
        {
            get { return global::LC.RA.TransferObjects.LocationsProtoReflection.Descriptor.MessageTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor
        {
            get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public LocationProto()
        {
            OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public LocationProto(LocationProto other) : this()
        {
            name_ = other.name_;
            region_ = other.region_;
            gpslocation_ = other.gpslocation_;
            _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public LocationProto Clone()
        {
            return new LocationProto(this);
        }

        /// <summary>Field number for the "name" field.</summary>
        public const int NameFieldNumber = 1;
        private string name_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string Name
        {
            get { return name_; }
            set
            {
                name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
        }

        /// <summary>Field number for the "region" field.</summary>
        public const int RegionFieldNumber = 2;
        private string region_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string Region
        {
            get { return region_; }
            set
            {
                region_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
        }

        /// <summary>Field number for the "gpslocation" field.</summary>
        public const int GpslocationFieldNumber = 3;
        private string gpslocation_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string Gpslocation
        {
            get { return gpslocation_; }
            set
            {
                gpslocation_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other)
        {
            return Equals(other as LocationProto);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(LocationProto other)
        {
            if (ReferenceEquals(other, null))
            {
                return false;
            }
            if (ReferenceEquals(other, this))
            {
                return true;
            }
            if (Name != other.Name) return false;
            if (Region != other.Region) return false;
            if (Gpslocation != other.Gpslocation) return false;
            return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode()
        {
            int hash = 1;
            if (Name.Length != 0) hash ^= Name.GetHashCode();
            if (Region.Length != 0) hash ^= Region.GetHashCode();
            if (Gpslocation.Length != 0) hash ^= Gpslocation.GetHashCode();
            if (_unknownFields != null)
            {
                hash ^= _unknownFields.GetHashCode();
            }
            return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString()
        {
            return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output)
        {
            if (Name.Length != 0)
            {
                output.WriteRawTag(10);
                output.WriteString(Name);
            }
            if (Region.Length != 0)
            {
                output.WriteRawTag(18);
                output.WriteString(Region);
            }
            if (Gpslocation.Length != 0)
            {
                output.WriteRawTag(26);
                output.WriteString(Gpslocation);
            }
            if (_unknownFields != null)
            {
                _unknownFields.WriteTo(output);
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize()
        {
            int size = 0;
            if (Name.Length != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
            }
            if (Region.Length != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(Region);
            }
            if (Gpslocation.Length != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(Gpslocation);
            }
            if (_unknownFields != null)
            {
                size += _unknownFields.CalculateSize();
            }
            return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(LocationProto other)
        {
            if (other == null)
            {
                return;
            }
            if (other.Name.Length != 0)
            {
                Name = other.Name;
            }
            if (other.Region.Length != 0)
            {
                Region = other.Region;
            }
            if (other.Gpslocation.Length != 0)
            {
                Gpslocation = other.Gpslocation;
            }
            _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input)
        {
            uint tag;
            while ((tag = input.ReadTag()) != 0)
            {
                switch (tag)
                {
                    default:
                        _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                        break;
                    case 10:
                        {
                            Name = input.ReadString();
                            break;
                        }
                    case 18:
                        {
                            Region = input.ReadString();
                            break;
                        }
                    case 26:
                        {
                            Gpslocation = input.ReadString();
                            break;
                        }
                }
            }
        }
    }

    public sealed partial class LocationsProto : pb::IMessage<LocationsProto>
    {
        private static readonly pb::MessageParser<LocationsProto> _parser = new pb::MessageParser<LocationsProto>(() => new LocationsProto());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<LocationsProto> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor
        {
            get { return global::LC.RA.TransferObjects.LocationsProtoReflection.Descriptor.MessageTypes[1]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor
        {
            get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public LocationsProto()
        {
            OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public LocationsProto(LocationsProto other) : this()
        {
            locations_ = other.locations_.Clone();
            _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public LocationsProto Clone()
        {
            return new LocationsProto(this);
        }

        /// <summary>Field number for the "locations" field.</summary>
        public const int LocationsFieldNumber = 1;
        private static readonly pb::FieldCodec<global::LC.RA.TransferObjects.LocationProto> _repeated_locations_codec
            = pb::FieldCodec.ForMessage(10, global::LC.RA.TransferObjects.LocationProto.Parser);
        private readonly pbc::RepeatedField<global::LC.RA.TransferObjects.LocationProto> locations_ = new pbc::RepeatedField<global::LC.RA.TransferObjects.LocationProto>();
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public pbc::RepeatedField<global::LC.RA.TransferObjects.LocationProto> Locations
        {
            get { return locations_; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other)
        {
            return Equals(other as LocationsProto);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(LocationsProto other)
        {
            if (ReferenceEquals(other, null))
            {
                return false;
            }
            if (ReferenceEquals(other, this))
            {
                return true;
            }
            if (!locations_.Equals(other.locations_)) return false;
            return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode()
        {
            int hash = 1;
            hash ^= locations_.GetHashCode();
            if (_unknownFields != null)
            {
                hash ^= _unknownFields.GetHashCode();
            }
            return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString()
        {
            return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output)
        {
            locations_.WriteTo(output, _repeated_locations_codec);
            if (_unknownFields != null)
            {
                _unknownFields.WriteTo(output);
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize()
        {
            int size = 0;
            size += locations_.CalculateSize(_repeated_locations_codec);
            if (_unknownFields != null)
            {
                size += _unknownFields.CalculateSize();
            }
            return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(LocationsProto other)
        {
            if (other == null)
            {
                return;
            }
            locations_.Add(other.locations_);
            _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input)
        {
            uint tag;
            while ((tag = input.ReadTag()) != 0)
            {
                switch (tag)
                {
                    default:
                        _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                        break;
                    case 10:
                        {
                            locations_.AddEntriesFrom(input, _repeated_locations_codec);
                            break;
                        }
                }
            }
        }
    }

    #endregion
}

#endregion Designer generated code
