image:
- Visual Studio 2019

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

configuration:
  - ReleaseWithoutDocker

install:
- cmd: >-
    appveyor DownloadFile https://dot.net/v1/dotnet-install.ps1
    powershell -NoLogo -NoProfile -File dotnet-install.ps1 -Version 3.0.100 -InstallDir "%ProgramFiles%\dotnet" -Architecture x64
    powershell -NoLogo -NoProfile -File dotnet-install.ps1 -Version 3.0.100 -InstallDir "%ProgramFiles(x86)%\dotnet" -Architecture x86

before_build:
  - dotnet restore ReviewApp.All.sln

build:
  parallel: true
  project: ReviewApp.All.sln

branches:  
  only:
  - master

test:
  categories:
    except:
    - IntegrationTests
