version: '3.4'

services:
  reviewapp.web.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  reviewapp.location.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
