version: '3'

services:
  lc.ra.web.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000"
  lc.ra.location.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001"
networks:
  default:
    external:
      name: nat
